"""empty message

Revision ID: 118b631aeb62
Revises: 8649835971df
Create Date: 2023-05-03 09:18:41.204967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118b631aeb62'
down_revision = '8649835971df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=60), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('code', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
