"""empty message

Revision ID: 724fd2ab86cf
Revises: 4e43b8e7aa2b
Create Date: 2023-05-10 10:31:56.304568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724fd2ab86cf'
down_revision = '4e43b8e7aa2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
